### ISSUE TITLE
Shared memory do not work at all

### ISSUE THREAD

**Issue by JanuszChmiel** [ZhymabekRoman/Exagear-For-Termux#15] opened 2022-04-30 18:57 UTC
Dear MR Roman, do you think, that it would be extremely complex to add The similar shared memory support, like in Proot for AArch 64 BIT systems? And how complex would be to recode Exagear so sound could work or espeak-ng could speak?
I have tested your app and for compiling and making packages, it is fast and reliable solution. Much faster than Proot usermode with qemu.
And no crashes.

**Comment by ZhymabekRoman** [comment] 2022-05-03 02:18
Hello, I was kind of adding Shared memory support. Okay, I'll see what's wrong.

> recode Exagear so sound could work or espeak-ng could speak

Try all the steps as in proot-distro, it should work - https://github.com/termux/proot-distro/issues/85#issuecomment-854358933

**Comment by ZhymabekRoman** [comment] 2022-06-21 11:23
Cannot reproduce the problem. Provide a real-life example

**Comment by ZhymabekRoman** [comment] 2022-10-29 00:56
I am closing the issue due to the inability to reproduce the problem

**Closed by ZhymabekRoman** 2022-10-29 00:56 UTC
Labels: help wanted, wontfix, unconfirmed
