### ISSUE TITLE
"Segmentation fault" error while booting up

### ISSUE THREAD

**Issue by Afk-82** [ZhymabekRoman/Exagear-For-Termux#6] opened 2021-05-21 23:56 UTC
Hello, I have followed the readme carefully, but whatever i try, "Segmentation fault" error will occur while starting x86 environment.
![image](https://user-images.githubusercontent.com/64241834/118997427-3d18f200-b9bb-11eb-8af2-f7dfbc6ba5f0.png)
Phone model: Huawei mate30 pro 5G
Operation System: EMUI 11.0.0 (Android 10)

From the start, I'm using a modified version of Termux named UTermux, so I did as the readme again in the official Termux (v0.112).
Tried to use newer version of Debian (2021.01.10) and Ubuntu (2020.12.10) image instead.
Tried to download data outside Termux then copy inside it instead of using git and wget.
All of above didn't work and got the same error.

Is worth nothing that, I always got the same tar error uncompress these system images, this may why the issue.
Found `tar: debian-buster-i386-2020.12.05/usr/bin/gunzip: Cannot hard link to ‘debian-buster-i386-2020.12.05/usr/bin/uncompress’: Permission denied` after log to file (line 6115,6282), but my phone can't be rooted, that's impossible to use sudo.
The error won't happen if test it with the same command in Linux for WIndows 10.
[log.txt](https://github.com/ZhymabekRoman/Exagear-For-Termux/files/6525496/log.txt)

Please consider to help me.
BTW, you may like to add `pkg install wget -y` to the readme, since wget isn't preset in Termux.

**Comment by ZhymabekRoman** [comment] 2021-05-25 05:07
Sorry for taking so long to answer. In general, I can assume that this problem concerns the firmware of the Huawei device, because even Exagear Windows does not work on all Huawei devices

**Comment by ZhymabekRoman** [comment] 2021-05-25 05:08
> BTW, you may like to add `pkg install wget -y` to the readme, since wget isn't preset in Termux.

Thank you very much, yes indeed I forgot to add

**Comment by ZhymabekRoman** [comment] 2022-10-29 00:58
I am closing the issue due to the inability to reproduce the problem

**Closed by ZhymabekRoman** 2022-10-29 00:58 UTC
Labels: help wanted, invalid, wontfix, unconfirmed

**Comment by DulavJ** [comment] 2023-09-18 17:23
Hi there,
I'm looking for someone everywhere until I find you who can help me in my current situation. I need help about creating OBB for wine 2.0 (exagear) please. That's why i'm contacting you today. Please do something for me bro, don't ignore me.

**Comment by DulavJ** [comment] 2023-09-18 17:32
Honestly i'm beginner, so help me please because i really need to use this wine 2.0 on exagear.

Email: dulavmultiservices19@gmail.com

**Comment by ZhymabekRoman** [comment] 2023-09-19 02:36
Do you have Telegram? Pm me if you have @Lalaleiman

**Comment by DulavJ** [comment] 2023-09-19 03:40
Ok, thanks in advance bro.

**Comment by DulavJ** [comment] 2023-09-19 03:58
I just sent my telegram
